config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get '/reservations/choose', to: 'reservations#choose'
  get '/reservations/results', to: 'reservations#results', as: :results
  resources :reservations, except: [:edit, :update, :destroy]
  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
# Reservation
class Reservation < ApplicationRecord
end

app/controllers/reservations_controller.rb
# reservations Controller
class ReservationsController < ApplicationController
  include CrawlerHelper
  before_action :verify_session

  def index; end

  def choose
    @centers = Crawler::CENTER_CODES.keys
  end

  def new
    @place = params[:center]
    @rooms = Crawler.instance.rooms(@place)
    @page = Crawler.instance.reservations_page(@place)
  end

  def create
    params = reservation_params
    rooms = params[:rooms] - ['0']
    base_reservation = Reservation.new(params.except(:rooms, :date, :start_time))
    base_reservation.datetime = "#{params[:date]} #{params[:start_time]}"
    base_reservation.token = User.new(session[:user]).encrypted
    if (base_reservation.datetime.to_date - Date.today).to_i > CrawlerHelper::MAX_FORWARD[params[:place]]
      base_reservation.status = 'Reserva Futura'
    else
      base_reservation.status = 'Processando Reserva'
    end
    reservations = []
    rooms.each do |room|
      reservation = base_reservation.dup
      reservation.room = CrawlerHelper::CCSUL_ROOMS.invert[room]
      reservation.save
      ReservationJob.perform_now(reservation) if reservation.status == 'Processando Reserva'
      reservations << reservation
    end

    redirect_to results_path, reservations: reservations
  end

  def results
    @reservations = params[:reservations]
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      :name, :date, :start_time, :finish_time,
      :members, :organization, :division, :place, rooms: []
    )
  end

  def verify_session
    redirect_to root_path unless session[:user].present?
  end
end

app/views/reservations/choose.html.haml
%h1 Escolha a sede:

.flex
  - @centers.each do |center|
    = link_to center, new_reservation_path(center: center), class: 'link'

= link_to 'Voltar', root_path

app/views/reservations/create.js.erb
$(document).ready(function() {  
  salas = '';  
  $('#reservation-message').empty();
  $('#reservation-message').append(
    "<% if success.length > 0 %>" +
      "As seguintes salas foram reservadas: " +
      "<% success.each do |room| %>"+
        "<%= "#{room} " %>" +
        "<% end %>" +
      "<br>Favor conferir a reserva na extranet!" +
    "<% else %>" +
      "Nenhuma reserva foi realizada..." +
    "<% end %>"
  );
});

app/views/reservations/new.html.haml
%h1 Reserva de Salas

.reservations-container
  .form-container

    #reservation-message

    = button_tag 'Ongakutai', type: 'button', id: 'fill-form'

    = form_for :reservation, url: '/reservations', remote: true, html: {id: 'reservation-form'} do |f|

      .fields

        = f.label 'Nome padrão da atividade:'
        = f.text_field :name

        = f.label 'Organização:'
        = f.text_field :organization

        = f.label 'Divisão (1 = 5D, 13 = GH):'
        = f.text_field :division

        = f.label 'Data (dd/mm/aaaa):'
        = f.text_field :date

        = f.label 'Horário de início (hh:mm):'
        = f.text_field :start_time

        = f.label 'Horário de término (hh:mm):'
        = f.text_field :finish_time

        = f.label 'Número previsto de membros:'
        = f.text_field :members

        = f.hidden_field :place, value: @place

      .rooms
        %h3 Salas a serem reservadas:
        - @rooms.each do |number, room|
          = f.label "rooms_#{number}" do
            = f.check_box :rooms, { multiple: true }, number
            = room

      = f.submit 'Reservar', id: 'reservation-submit'

      = link_to 'Voltar', reservations_choose_path

  .reservations
    %h2 Salas reservadas no mês
    = @page

app/views/reservations/results.html.haml
Oi